name: Build TAD Delivery Tool

on:
  push:
    branches: ["*"]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: ["*"]
    paths-ignore:
      - 'README.md'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:20241104
    name: Build with Docker using devkitARM
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup environment
        run: git config --global safe.directory '*'
      - name: Build TAD Delivery Tool
        run: make
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v4.3.6
        with:
          path: "TDT.dsi"
          name: TDT-Nightly-Unsigned

  devsign:
    runs-on: windows-latest
    needs: [build]
    name: Devsign TDT and build a TAD
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: TDT-Nightly-Unsigned
          path: D:\a\TDT\TDT\TDT-Build
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Clone ntool
        uses: GuillaumeFalourd/clone-github-repo-action@v2.1
        with:
          depth: 1
          owner: 'xprism1'
          repository: 'ntool'
      - name: Devsign TAD Delivery Tool
        run: |
          cp TDT-Build\TDT.dsi ntool
          cd ntool
          pip install pycryptodome
          python ntool.py srl_retail2dev TDT.dsi
      - name: Publish devsigned build to GH Actions
        uses: actions/upload-artifact@v4.3.6
        with:
          path: "ntool/TDT_dev.srl"
          name: TDT-Nightly-Devsigned
      - name: Make a devsigned TAD
        run: |
          curl https://cdn.randommeaninglesscharacters.com/tools/maketad/maketad.zip -o maketad.zip
          7z e maketad.zip
          cp ntool/TDT_dev.srl .
          .\maketad-20090604.exe TDT_dev.srl -s -o TDT-Nightly.tad
      - name: Publish devsigned TAD to GH Actions
        uses: actions/upload-artifact@v4.3.6
        with:
          path: "TDT-Nightly.tad"
          name: TDT-Nightly-TAD

  # Only run this for non-PR jobs.
  publish_build:
    runs-on: ubuntu-latest
    name: Upload to release
    if: ${{ success() && startsWith(github.ref, 'refs/tags') }}
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Publish Build
        run: |
          ID=$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)

          for file in ${{ github.workspace }}/build/*; do
            AUTH_HEADER="Authorization: token ${{ secrets.GITHUB_TOKEN }}"
            CONTENT_LENGTH="Content-Length: $(stat -c%s $file)"
            CONTENT_TYPE="Content-Type: application/7z-x-compressed"
            UPLOAD_URL="https://uploads.github.com/repos/${{ github.repository }}/releases/$ID/assets?name=$(basename $file)"

            curl -XPOST -H "$AUTH_HEADER" -H "$CONTENT_LENGTH" -H "$CONTENT_TYPE" --upload-file "$file" "$UPLOAD_URL"
          done
